# Generated by Django 6.0.5 on 2026-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('TERMINO_FIJO', 'Término Fijo'), ('TERMINO_INDEFINIDO', 'Término Indefinido'), ('OBRA_LABOR', 'Obra Labor'), ('PRESTACION_SERVICIOS', 'Prestación de Servicios')], max_length=30)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('eps', models.CharField(max_length=100)),
                ('afp', models.CharField(max_length=100)),
                ('arl', models.CharField(max_length=100)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=30, null=True)),
                ('banco', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20, null=True)),
                ('foto_facial', models.TextField(blank=True, null=True)),
                ('foto_facial_registrada', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
