# Generated by Django 6.0.5 on 2026-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_sede',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
