# Generated by Django 6.0.5 on 2026-05-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_id_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id_sede',
        ),
    ]
