# Generated by Django 6.0.5 on 2026-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_parametrosistema_empleado_user_asistencia_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='liveness_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Puntuación de detección de vitalidad (0-1)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='liveness_validated',
            field=models.BooleanField(default=False, help_text='Indica si pasó la validación de vitalidad'),
        ),
    ]
