# Generated by Django 6.0.5 on 2026-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_asistencia_liveness_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='afp',
            field=models.CharField(choices=[('Porvenir', 'Porvenir'), ('Colfondos', 'Colfondos'), ('Protección', 'Protección'), ('Old Mutual', 'Old Mutual'), ('Skandia', 'Skandia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='arl',
            field=models.CharField(choices=[('Positiva', 'Positiva'), ('Sura', 'Sura'), ('Bolívar', 'Bolívar'), ('Colpatria', 'Colpatria'), ('Mapfre', 'Mapfre'), ('Colmena', 'Colmena'), ('Equidad', 'Equidad'), ('Aurora', 'Aurora'), ('Seguros del Estado', 'Seguros del Estado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='banco',
            field=models.CharField(blank=True, choices=[('Bancolombia', 'Bancolombia'), ('Davivienda', 'Davivienda'), ('Banco de Bogotá', 'Banco de Bogotá'), ('Banco Popular', 'Banco Popular'), ('Banco de Occidente', 'Banco de Occidente'), ('BBVA', 'BBVA'), ('Colpatria', 'Colpatria'), ('AV Villas', 'AV Villas'), ('Itaú', 'Itaú'), ('Banco Agrario', 'Banco Agrario'), ('Bancoomeva', 'Bancoomeva'), ('Scotiabank Colpatria', 'Scotiabank Colpatria'), ('Banco Caja Social', 'Banco Caja Social'), ('Nequi', 'Nequi'), ('DaviPlata', 'DaviPlata')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('Desarrollador Senior', 'Desarrollador Senior'), ('Desarrollador Junior', 'Desarrollador Junior'), ('Analista de Calidad', 'Analista de Calidad'), ('Analista de Desarrollo', 'Analista de Desarrollo'), ('Diseñador UX/UI', 'Diseñador UX/UI'), ('Scrum Master', 'Scrum Master'), ('Product Owner', 'Product Owner'), ('Administrador de RRHH', 'Administrador de RRHH'), ('Contador General', 'Contador General'), ('Gerente General', 'Gerente General'), ('Administrador del Sistema', 'Administrador del Sistema'), ('Auxiliar Contable', 'Auxiliar Contable'), ('Secretario(a)', 'Secretario(a)'), ('Practicante', 'Practicante')], max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='eps',
            field=models.CharField(choices=[('Sanitas', 'Sanitas'), ('Nueva EPS', 'Nueva EPS'), ('Compensar', 'Compensar'), ('Colsanitas', 'Colsanitas'), ('Sura', 'Sura'), ('Salud Total', 'Salud Total'), ('Coomeva', 'Coomeva'), ('Famisanar', 'Famisanar'), ('Cafam', 'Cafam'), ('Cruz Blanca', 'Cruz Blanca'), ('Capital Salud', 'Capital Salud'), ('Mutual Ser', 'Mutual Ser'), ('Comfamiliar', 'Comfamiliar')], max_length=100),
        ),
    ]
