# Generated by Django 6.0.2 on 2026-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_empleado_afp_alter_empleado_arl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('EXITO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('RECHAZADO', 'Rechazado'), ('FRAUDE', 'Intento de fraude')], default='EXITO', max_length=20),
        ),
    ]
