# Generated by Django 6.0.5 on 2026-05-26 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_asistencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionNomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_extra_diurnas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_extra_nocturnas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_dominicales', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recargo_diurno', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recargo_nocturno', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recargo_dominical', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_salud', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_pension', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_arl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_liquidados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('CALCULADA', 'Calculada'), ('LIQUIDADA', 'Liquidada'), ('ANULADA', 'Anulada')], default='CALCULADA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='empleados.empleado')),
            ],
            options={
                'db_table': 'liquidaciones_nomina',
                'ordering': ['-periodo_fin', 'empleado__apellidos'],
                'unique_together': {('empleado', 'periodo_inicio', 'periodo_fin')},
            },
        ),
        migrations.CreateModel(
            name='Desprendible',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('archivo_pdf', models.TextField(blank=True, help_text='Contenido base64 del PDF', null=True)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='GENERADO', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('email_enviado_a', models.EmailField(blank=True, max_length=254, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desprendibles', to='empleados.empleado')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desprendibles', to='empleados.liquidacionnomina')),
            ],
            options={
                'db_table': 'desprendibles',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
