# Generated by Django 6.0.6 on 2026-06-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_asistencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_nomina', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'nominas',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_extra_diurnas', models.IntegerField(default=0)),
                ('horas_extra_nocturnas', models.IntegerField(default=0)),
                ('devengado_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_salud', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_pension', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deducciones_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='empleados.empleado')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='empleados.nomina')),
            ],
            options={
                'db_table': 'detalles_nomina',
            },
        ),
    ]
