# Generated by Django 6.0.5 on 2026-05-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_liquidacionnomina_desprendible'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionnomina',
            name='salario_base_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario base original antes de ajuste SMMLV', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='liquidacionnomina',
            name='smmlv_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del SMMLV usado en el cálculo', max_digits=12, null=True),
        ),
    ]
